title: Ian Atroshchenko
description: Personal website of Ian Atroshchenko
url: https://ian-va.github.io

permalink: /posts/:year/:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
